baseURL = "https://Seigenkousya.github.io/"
languageCode = "ja"
theme = "hugo-theme-m10c"
title = "正弦工社"

publishdir="public"
pygmentsCodeFences=true
googleAnalytics="UA-158095539-1"

[params]
author = "Takana Norimasa"
description="正弦工社 is 技術{同人|結社|集団|コミュニティ|ブログ} "
logo = "/images/logo.png"

[[params.social]]
	name = "twitter"
	url = "https://twitter.com/Seigenkousya"

[[params.social]]
	name = "github"
	url = "https://github.com/Seigenkousya"

[[params.social]]
	name = "qiita"
	url = "https://qiita.com/Seigenkousya"
